theme[main_bg]=""
theme[main_fg]="#CDD6F4"
theme[title]="#E8E7FF"

theme[hi_fg]="#CBA6F7"
theme[selected_bg]="#40305F"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#6E7390"

theme[graph_text]="#B9B7D6"
theme[meter_bg]="#24263A"
theme[proc_misc]="#A6ADC8"

theme[cpu_box]="#CBA6F7"
theme[mem_box]="#89B4FA"
theme[net_box]="#74D7F7"
theme[proc_box]="#AFA8FF"

theme[div_line]="#45475A"

theme[temp_start]="#89B4FA"
theme[temp_mid]="#CBA6F7"
theme[temp_end]="#F38BA8"

theme[cpu_start]="#7AA2F7"
theme[cpu_mid]="#CBA6F7"
theme[cpu_end]="#F5C2E7"

theme[free_start]="#74D7F7"
theme[free_mid]="#89B4FA"
theme[free_end]="#A6E3A1"

theme[cached_start]="#45475A"
theme[cached_mid]="#6C7086"
theme[cached_end]="#A6ADC8"

theme[available_start]="#74D7F7"
theme[available_mid]="#89DCEB"
theme[available_end]="#A6E3A1"

theme[used_start]="#CBA6F7"
theme[used_mid]="#F5C2E7"
theme[used_end]="#F38BA8"

theme[download_start]="#74D7F7"
theme[download_mid]="#89B4FA"
theme[download_end]="#CBA6F7"

theme[upload_start]="#7AA2F7"
theme[upload_mid]="#CBA6F7"
theme[upload_end]="#F5C2E7"

theme[process_start]="#89B4FA"
theme[process_mid]="#CBA6F7"
theme[process_end]="#F38BA8"

theme[read_start]="#74D7F7"
theme[read_mid]="#89DCEB"
theme[read_end]="#A6E3A1"

theme[write_start]="#7AA2F7"
theme[write_mid]="#89B4FA"
theme[write_end]="#CBA6F7"